-- ============================================
-- TALPA Etkinlik Platform - MASTER SCHEMA V3.1.0 (FIXED)
-- ============================================
-- 1. All Tables (Profiles, Events, Bookings, Tickets)
-- 2. Migration Safety (Adds missing columns to existing tables)
-- 3. Function Drops (Fixes parameter name conflicts)
-- 4. RLS & Security (Recursion fixes)
-- ============================================

-- ============================================
-- 1. ENUM TYPES
-- ============================================

DO $$ BEGIN
    CREATE TYPE event_status AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE queue_status AS ENUM ('ASIL', 'YEDEK', 'IPTAL');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE payment_status AS ENUM ('WAITING', 'PAID');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ============================================
-- 2. TABLES & MIGRATION SAFETY
-- ============================================

-- 2.1 PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles Migration Checks
DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member'));
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS sicil_no TEXT UNIQUE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tckn TEXT UNIQUE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT UNIQUE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- 2.2 EVENTS
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Events Migration Checks (FIX FOR MISSING COLUMNS ERROR)
DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS description TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS banner_image TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS image_url TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS location TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS location_url TEXT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'TL';
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS quota_asil INT NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS quota_yedek INT NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS cut_off_date TIMESTAMP WITH TIME ZONE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE public.events ADD COLUMN IF NOT EXISTS status event_status DEFAULT 'DRAFT';
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- 2.3 BOOKINGS
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    queue_status queue_status NOT NULL,
    payment_status payment_status DEFAULT 'WAITING',
    booking_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    consent_kvkk BOOLEAN DEFAULT FALSE,
    consent_payment BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(event_id, user_id)
);

-- 2.4 TICKET POOL
CREATE TABLE IF NOT EXISTS public.ticket_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_at TIMESTAMP WITH TIME ZONE,
    is_assigned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 TICKETS (Legacy Support)
CREATE TABLE IF NOT EXISTS public.tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    qr_code TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================
-- 3. VIEWS & HELPERS
-- ============================================

-- Admin Check Helper (Security Definer)
CREATE OR REPLACE FUNCTION public.get_my_admin_status()
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT is_admin FROM profiles WHERE id = auth.uid()), false);
$$;

-- Updated At Trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = timezone('utc'::text, now()); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_events_updated_at ON public.events;
CREATE TRIGGER set_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_bookings_updated_at ON public.bookings;
CREATE TRIGGER set_bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Active Event View (Safe Drop & Recreate)
DROP VIEW IF EXISTS public.active_event_view;

CREATE OR REPLACE VIEW public.active_event_view AS
SELECT 
    e.id,
    e.title,
    e.description,
    COALESCE(e.banner_image, e.image_url) as image_url,
    e.event_date,
    COALESCE(e.location_url, e.location) as location,
    e.price,
    e.currency,
    e.quota_asil + e.quota_yedek as total_quota,
    CASE WHEN e.status = 'ACTIVE' THEN true ELSE false END as is_active,
    e.created_at,
    e.updated_at,
    COALESCE(
        (e.quota_asil + e.quota_yedek) - (
            SELECT COUNT(*)
            FROM public.bookings b
            WHERE b.event_id = e.id 
            AND b.queue_status IN ('ASIL', 'YEDEK')
        ), 
        e.quota_asil + e.quota_yedek
    ) AS remaining_stock
FROM public.events e
WHERE e.status = 'ACTIVE';

-- ============================================
-- 4. LOGIC FUNCTIONS (FIXED)
-- ============================================

-- FIX: DROP before CREATE to handle parameter name changes
DROP FUNCTION IF EXISTS public.join_event(bigint);

CREATE OR REPLACE FUNCTION public.join_event(p_event_id BIGINT)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_current_asil_count INT;
  v_current_yedek_count INT;
  v_event_record RECORD;
  v_user_id UUID;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN RETURN json_build_object('success', false, 'error_code', 'AUTH_REQUIRED', 'message', 'Giriş yapmalısınız.'); END IF;

  SELECT * INTO v_event_record FROM events WHERE id = p_event_id FOR UPDATE;
  
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'error_code', 'EVENT_NOT_FOUND', 'message', 'Etkinlik bulunamadı.'); END IF;
  IF v_event_record.status != 'ACTIVE' THEN RETURN json_build_object('success', false, 'error_code', 'EVENT_NOT_ACTIVE', 'message', 'Etkinlik aktif değil.'); END IF;
  IF v_event_record.cut_off_date IS NOT NULL AND NOW() > v_event_record.cut_off_date THEN RETURN json_build_object('success', false, 'error_code', 'REGISTRATION_CLOSED', 'message', 'Başvuru süresi sona ermiştir.'); END IF;
  
  IF EXISTS (SELECT 1 FROM bookings WHERE event_id = p_event_id AND user_id = v_user_id) THEN
    RETURN json_build_object('success', false, 'error_code', 'ALREADY_REGISTERED', 'message', 'Zaten bu etkinliğe başvurunuz var.');
  END IF;

  SELECT COUNT(*) INTO v_current_asil_count FROM bookings WHERE event_id = p_event_id AND queue_status = 'ASIL';
  IF v_current_asil_count < v_event_record.quota_asil THEN
    INSERT INTO bookings (event_id, user_id, queue_status, consent_kvkk, consent_payment) VALUES (p_event_id, v_user_id, 'ASIL', true, true);
    RETURN json_build_object('success', true, 'queue', 'ASIL', 'position', v_current_asil_count + 1, 'message', 'Başvurunuz alındı. Asil listedesiniz.');
  END IF;

  SELECT COUNT(*) INTO v_current_yedek_count FROM bookings WHERE event_id = p_event_id AND queue_status = 'YEDEK';
  IF v_current_yedek_count < v_event_record.quota_yedek THEN
    INSERT INTO bookings (event_id, user_id, queue_status, consent_kvkk, consent_payment) VALUES (p_event_id, v_user_id, 'YEDEK', true, true);
    RETURN json_build_object('success', true, 'queue', 'YEDEK', 'position', v_current_yedek_count + 1, 'message', 'Başvurunuz alındı. Yedek listedesiniz.');
  END IF;

  RETURN json_build_object('success', false, 'error_code', 'QUOTA_FULL', 'message', 'Kontenjan dolmuştur.');
EXCEPTION WHEN OTHERS THEN RETURN json_build_object('success', false, 'error_code', 'INTERNAL_ERROR', 'message', 'Hata oluştu.', 'details', SQLERRM);
END;
$$;

-- FIX: DROP before CREATE
DROP FUNCTION IF EXISTS public.assign_ticket(bigint);

CREATE OR REPLACE FUNCTION public.assign_ticket(p_booking_id BIGINT)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_booking_record RECORD;
  v_ticket_record RECORD;
BEGIN
  IF NOT public.get_my_admin_status() THEN RETURN json_build_object('success', false, 'error_code', 'UNAUTHORIZED', 'message', 'Yetkiniz yok.'); END IF;

  SELECT * INTO v_booking_record FROM bookings WHERE id = p_booking_id AND payment_status = 'WAITING' FOR UPDATE SKIP LOCKED;
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'error_code', 'BOOKING_NOT_FOUND', 'message', 'Başvuru bulunamadı veya işlemde.'); END IF;

  SELECT * INTO v_ticket_record FROM ticket_pool WHERE event_id = v_booking_record.event_id AND is_assigned = false ORDER BY file_name ASC LIMIT 1 FOR UPDATE SKIP LOCKED;
  IF NOT FOUND THEN RETURN json_build_object('success', false, 'error_code', 'NO_TICKETS_AVAILABLE', 'message', 'Bilet yok.'); END IF;

  UPDATE ticket_pool SET assigned_to = v_booking_record.user_id, assigned_at = NOW(), is_assigned = true WHERE id = v_ticket_record.id;
  UPDATE bookings SET payment_status = 'PAID' WHERE id = p_booking_id;

  RETURN json_build_object('success', true, 'ticket_id', v_ticket_record.id, 'file_path', v_ticket_record.file_path, 'message', 'Bilet atandı.');
EXCEPTION WHEN OTHERS THEN RETURN json_build_object('success', false, 'error_code', 'INTERNAL_ERROR', 'message', 'Hata oluştu.', 'details', SQLERRM);
END;
$$;

-- FIX: DROP before CREATE
DROP FUNCTION IF EXISTS public.set_active_event(bigint);

CREATE OR REPLACE FUNCTION public.set_active_event(p_event_id BIGINT)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_exists BOOLEAN;
BEGIN
  IF NOT public.get_my_admin_status() THEN RETURN json_build_object('success', false, 'message', 'Yetkiniz yok.'); END IF;
  SELECT EXISTS (SELECT 1 FROM events WHERE id = p_event_id) INTO v_exists;
  IF NOT v_exists THEN RETURN json_build_object('success', false, 'message', 'Etkinlik bulunamadı.'); END IF;
  
  UPDATE events SET status = 'ARCHIVED' WHERE status = 'ACTIVE';
  UPDATE events SET status = 'ACTIVE' WHERE id = p_event_id;
  RETURN json_build_object('success', true, 'message', 'Etkinlik aktif edildi.');
END;
$$;

-- ============================================
-- 5. RLS POLICIES
-- ============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_pool ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Clean existing policies
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles; 
DROP POLICY IF EXISTS "Admins can update any profile" ON public.profiles;
DROP POLICY IF EXISTS "Anyone can view active events" ON public.events;
DROP POLICY IF EXISTS "Admins can view all events" ON public.events;
DROP POLICY IF EXISTS "Admins can insert events" ON public.events;
DROP POLICY IF EXISTS "Admins can update events" ON public.events;
DROP POLICY IF EXISTS "Admins can delete events" ON public.events;
DROP POLICY IF EXISTS "Users view own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Admins manage all bookings" ON public.bookings;
DROP POLICY IF EXISTS "Users view assigned ticket" ON public.ticket_pool;
DROP POLICY IF EXISTS "Admins manage tickets" ON public.ticket_pool;

-- PROFILES
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING (public.get_my_admin_status() = true);
CREATE POLICY "Admins can update any profile" ON public.profiles FOR UPDATE USING (public.get_my_admin_status() = true);

-- EVENTS
CREATE POLICY "Anyone can view active events" ON public.events FOR SELECT USING (status = 'ACTIVE');
CREATE POLICY "Admins can view all events" ON public.events FOR SELECT USING (public.get_my_admin_status() = true);
CREATE POLICY "Admins can insert events" ON public.events FOR INSERT WITH CHECK (public.get_my_admin_status() = true);
CREATE POLICY "Admins can update events" ON public.events FOR UPDATE USING (public.get_my_admin_status() = true);
CREATE POLICY "Admins can delete events" ON public.events FOR DELETE USING (public.get_my_admin_status() = true);

-- BOOKINGS
CREATE POLICY "Users view own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins manage all bookings" ON public.bookings FOR ALL USING (public.get_my_admin_status() = true);

-- TICKET POOL
CREATE POLICY "Users view assigned ticket" ON public.ticket_pool FOR SELECT USING (assigned_to = auth.uid());
CREATE POLICY "Admins manage tickets" ON public.ticket_pool FOR ALL USING (public.get_my_admin_status() = true);

-- 3.4 CANCEL BOOKING (NEW)
CREATE OR REPLACE FUNCTION public.cancel_booking(booking_id_param BIGINT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  booking_record RECORD;
  event_record RECORD;
  user_id_var UUID;
BEGIN
  user_id_var := auth.uid();
  
  -- 1. Başvuru ve Etkinlik Bilgisini Al
  SELECT b.*, e.cut_off_date, e.status as event_status 
  INTO booking_record
  FROM public.bookings b
  JOIN public.events e ON e.id = b.event_id
  WHERE b.id = booking_id_param;

  -- 2. Yetki Kontrolü
  IF booking_record.user_id != user_id_var THEN
    RETURN json_build_object('status', 'error', 'message', 'Bu işlem için yetkiniz yok.');
  END IF;

  -- 3. Tarih Kontrolü (Sunucu Saati ile)
  IF booking_record.cut_off_date IS NOT NULL AND NOW() > booking_record.cut_off_date THEN
    RETURN json_build_object('status', 'error', 'message', 'İptal süresi dolmuştur.');
  END IF;

  -- 4. Durum Güncelleme
  UPDATE public.bookings
  SET queue_status = 'IPTAL', updated_at = NOW()
  WHERE id = booking_id_param;

  RETURN json_build_object('status', 'success', 'message', 'Başvurunuz iptal edildi.');
END;
$$;